import { loadConfig } from "./config.js";
import { Database } from "./infrastructure/database.js";
import { Store } from "./core/store.js";
import { GameService } from "./core/service.js";
import { DiscordRuntime } from "./discord/runtime.js";
import { Auth } from "./http/auth.js";
import { Files } from "./http/files.js";
import { createWebServer } from "./web-api.js";
import { JobRunner } from "./infrastructure/jobs.js";
const config=loadConfig();
const database=new Database(config.DATABASE_URL,config.SUPABASE_URL,config.SUPABASE_SERVICE_ROLE_KEY);
await database.query("SELECT 1 FROM schema_migrations WHERE name='002_runtime.sql'").then(r=>{if(!r.rowCount)throw new Error("Execute npm run db:migrate antes de iniciar");});
const service=new GameService(new Store(database),config.PRIVACY_SECRET??config.SESSION_SECRET);
const discord=new DiscordRuntime(service,config),files=new Files(database,config.FILES_DIR);
await discord.start();
const auth=new Auth(database,discord,{origin:config.WEB_ORIGIN,frontendOrigin:config.PANEL_ORIGIN??config.WEB_ORIGIN,frontendUrl:config.PANEL_URL??config.PANEL_ORIGIN??config.WEB_ORIGIN,clientId:config.DISCORD_CLIENT_ID,secure:config.NODE_ENV==="production"});
const server=createWebServer(service,auth,files),runner=new JobRunner(service,discord,files);
server.listen(config.WEB_PORT,config.WEB_HOST,()=>console.log(JSON.stringify({level:"info",event:"web.ready",origin:config.WEB_ORIGIN})));
if(config.RUN_WORKER)runner.start();
let stopping=false;
const stop=async()=>{if(stopping)return;stopping=true;await new Promise<void>(resolve=>server.close(()=>resolve()));await runner.stop();await discord.stop();await database.close();};
process.once("SIGINT",()=>{void stop();});process.once("SIGTERM",()=>{void stop();});

