import {Api,download} from './api.js';
import {modules,labels,field} from './catalog.js';
const api=new Api(),$=s=>document.querySelector(s);
let me=null,state=null,page=1,query='',generation=0,callback=null,descriptors=[],formBusy=false;
const node=(tag,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;if(className)n.className=className;return n;};
const button=(text,run,primary=false)=>{const n=node('button',text,primary?'primary-button':'secondary-button');n.type='button';n.addEventListener('click',async()=>{n.disabled=true;try{await run();}catch(e){feedback(e.message,true);}finally{n.disabled=false;}});return n;};
function feedback(text,error=false){const box=$('#feedback');box.textContent=text;box.className=text?`notice ${error?'error':''}`:'';}
function current(){const kind=location.hash.slice(1)||'dashboard';return modules[kind]?kind:'dashboard';}
function nav(){const root=$('#navigation');root.replaceChildren();let group='';for(const [kind,module] of Object.entries(modules)){if(module.admin&&!state?.capabilities.admin)continue;if(module.group!==group){root.append(node('p',module.group,'nav-label'));group=module.group;}const a=node('a',module.label,`nav-item ${current()===kind?'active':''}`);a.href=`#${kind}`;root.append(a);}}
function detail(label,value){const p=node('p');p.append(node('strong',`${label}: `),document.createTextNode(String(value)));return p;}
function setNested(target,path,value){const parts=path.split('.');let at=target;parts.forEach((p,i)=>{if(i===parts.length-1)at[p]=value;else at=at[p]??=(/^\d+$/.test(parts[i+1])?[]:{});});}
function getNested(target,path){return path.split('.').reduce((v,p)=>v?.[p],target);}
async function form(title,fields,onSubmit,description='',initial={}) {
  $('#dialogTitle').textContent=title;$('#dialogDescription').textContent=description;$('#formError').textContent='';$('#fields').replaceChildren();descriptors=fields;callback=onSubmit;
  for(const f of fields){const label=node('label','','field');label.append(node('span',f.label));let input;
    if(['select','division','member','season','assignment'].includes(f.type)){input=document.createElement('select');let options=f.options;
      if(f.type!=='select'){const result=await api.view(f.type);options=result.items.map(r=>({value:r.id??r.user_id,label:r.data?.name??r.name??r.display_name??r.id}));}
      for(const option of options){const value=typeof option==='object'?option.value:option,text=typeof option==='object'?option.label:labels[option]??option;const element=node('option',text);element.value=value;input.append(element);}
    }else if(['textarea','lines'].includes(f.type))input=document.createElement('textarea');else{input=document.createElement('input');input.type=f.type==='optional'?'text':f.type;}
    input.name=f.key;input.id=`field-${f.key}`;input.required=!['optional','checkbox'].includes(f.type);const value=getNested(initial,f.key)??f.value;
    if(f.type==='checkbox')input.checked=Boolean(value);else input.value=f.type==='lines'&&Array.isArray(value)?value.join('\n'):f.type==='datetime-local'&&value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):value;
    if(f.type==='number'){input.step='1';input.min=f.key==='amount'?'-1000':'0';}if(f.type==='password')input.autocomplete='new-password';
    label.append(input);$('#fields').append(label);
  }
  $('#editor').showModal();$('#fields').querySelector('input,select,textarea')?.focus();
}
$('#editorForm').addEventListener('submit',async e=>{
  e.preventDefault();if(formBusy)return;formBusy=true;$('#submitForm').disabled=true;$('#formError').textContent='';
  try{const data={};for(const f of descriptors){const input=document.getElementById(`field-${f.key}`);let value=f.type==='checkbox'?input.checked:f.type==='number'?Number(input.value):f.type==='datetime-local'?new Date(input.value).toISOString():f.type==='lines'?input.value.split('\n').map(v=>v.trim()).filter(Boolean):input.value;if(f.type==='optional'&&!value)continue;setNested(data,f.key,value);}
    if(typeof data.choice==='string' && /^\d+$/.test(data.choice))data.choice=Number(data.choice);
    const result=await callback(data);$('#editor').close();await load();feedback(result?.jobId?'Solicitação recebida. Acompanhe o progresso em Tarefas.':'Ação concluída.');
  }catch(error){$('#formError').textContent=error.message;}finally{formBusy=false;$('#submitForm').disabled=false;}
});
$('#closeDialog').addEventListener('click',()=>{if(!formBusy)$('#editor').close();});
$('#editor').addEventListener('cancel',e=>{if(formBusy)e.preventDefault();});
const act=(action,data)=>api.act(action,data);
const ask=(title,action,data,fields=[field('confirm','Confirmo esta ação','checkbox',false)],description='')=>form(title,fields,input=>act(action,{...data,...input}),description);
function definition(kind,row){return form(row?'Editar rascunho':`Criar ${modules[kind].label.toLowerCase()}`,modules[kind].fields,data=>act('definition.save',{kind,...(row?{id:row.id}:{}),data}),'Será salvo como rascunho. Revise antes de publicar.',row?.data??{});}
async function load(){
  if(!api.guild)return;const turn=++generation;$('#view').setAttribute('aria-busy','true');$('#refresh').disabled=true;feedback('Carregando…');
  try{state=await api.view('dashboard');if(turn!==generation)return;nav();const kind=current();$('#pageTitle').textContent=modules[kind].label;$('#pageDescription').textContent=state.settings.name;$('#toolbar').replaceChildren();$('#pagination').replaceChildren();
    const data=['dashboard','privacy'].includes(kind)?state:await api.view(kind,page,query);if(turn!==generation)return;$('#view').replaceChildren();
    if(kind==='dashboard')dashboard2(data);else if(kind==='privacy')privacy();else if(kind==='settings')settings(data);else if(kind==='metrics')metrics(data);else render(kind,data);
    feedback('');$('#connection').textContent='Conectado ao servidor';
  }catch(error){if(turn===generation){feedback(error.message,true);$('#view').replaceChildren(node('p','Os dados não puderam ser carregados. Use Atualizar para tentar novamente.','empty'));}}
  finally{if(turn===generation){$('#view').removeAttribute('aria-busy');$('#refresh').disabled=false;}}
}
function dashboard(data){
  const root=$('#view'),stats=node('div','','stats-grid');
  for(const [label,value] of [['SEU XP',data.member?.xp??0],['CRÉDITOS',data.member?.credits??0],['PARTICIPANTES',data.stats.members],['DIVISÕES',data.stats.divisions]]){const card=node('article','','stat-card');const body=node('div');body.append(node('span',label),node('strong',String(value)));card.append(body);stats.append(card);}root.append(stats);
  const card=node('article','','record-card');card.append(node('p','SUA PRÓXIMA AÇÃO','eyebrow'),node('h2',data.member?.participation==='active'?'Continue sua jornada.':'Entre para a base.'));
  card.append(node('p',data.member?.participation==='active'?'Encontre uma divisão, participe de uma missão ou acompanhe o próximo evento.':'A participação é opcional. Ao aceitar, o bot registra seu progresso e atividades elegíveis neste servidor. Você pode exportar seus dados e sair quando quiser.'));
  card.append(data.member?.participation==='active'?button('Ver minhas missões',()=>{location.hash='assignment';},true):button('Aceitar e participar',async()=>{await act('consent',{accept:true});await load();},true));root.append(card);
  if(data.season){const season=node('article','','record-card');season.append(node('h2',data.season.data.name),node('p',data.season.data.theme));root.append(season);}
  if(data.capabilities.admin){$('#toolbar').append(button('Configurar base',()=>setup()),button('Sincronizar membros',()=>ask('Sincronizar membros','members.sync',{},[], 'Cadastra humanos como recrutas; não concede consentimento.')),button('Criar conteúdo por template',()=>templates()));
    if(data.jobs?.length){const card=node('article','','record-card');card.append(node('h2','Operações recentes'));for(const job of data.jobs)card.append(detail(job.kind,labels[job.status]??job.status));card.append(button('Acompanhar tarefas',()=>{location.hash='job';}));root.append(card);}}
}
function setup(){return form('Configurar a base',[field('name','Nome da gangue'),field('color','Cor','color','#8B1E2D'),field('count','Quantidade de divisões','number',2),field('memberLimit','Vagas por divisão','number',25)],async data=>{
  const preview=await act('setup.draft',data);$('#editor').close();setTimeout(()=>{void form('Confirmar estrutura',[field('confirm','Confirmo a criação dos cargos, canais e divisões','checkbox',false)],input=>act('setup.confirm',{...data,...input}),`Serão preparados: ${preview.preview.divisions.join(', ')}. Canais: ${preview.preview.channels.join(', ')}.`);},0);return preview;
},'A primeira etapa salva um rascunho e mostra a prévia.');}
function privacy(){const root=$('#view');root.append(node('p','Sua participação é opcional. A saída remove seu perfil, provas e preferências; mantém apenas referências protegidas necessárias ao histórico e à prevenção de recompensas duplicadas.','notice'));
  root.append(button('Exportar meus dados',async()=>download(new Blob([JSON.stringify(await act('privacy.export',{}),null,2)],{type:'application/json'}),'meus-dados-jumanji.json')));
  root.append(button('Preferências de notificação',()=>form('Notificações',[field('notifications','Receber lembretes de eventos','checkbox',state.member?.preferences?.notifications??true),field('reactivation','Receber convite opcional para retornar','checkbox',state.member?.preferences?.reactivation??false)],data=>act('privacy.preferences',data))));
  root.append(button('Gerar card para compartilhar',()=>form('Card de perfil',[field('format','Formato','select','post',['post','story']),field('hideIdentity','Ocultar nome e estatísticas','checkbox',false)],async data=>{const blob=await api.request(`/api/guilds/${encodeURIComponent(api.guild)}/card`,{method:'POST',body:JSON.stringify(data)});download(blob,'jumanji.png');return {};})));
  root.append(button('Sair do RPG e excluir perfil',()=>ask('Excluir meu perfil','privacy.leave',{},[field('confirm','Confirmo a saída e exclusão do perfil','checkbox',false)],'Esta ação remove sua participação e interrompe recompensas. Você poderá entrar novamente por consentimento explícito.')));
}
function settings(data){const root=$('#view');root.append(node('p','Revise as regras antes de salvar. Recursos avançados e poderes de moderação começam desativados.','notice'));root.append(button('Editar configurações',()=>form('Regras do servidor',[
  field('name','Nome'),field('color','Cor','color'),field('timezone','Fuso horário'),field('entryMode','Entrada nas divisões','select','free',['free','invite','balanced','quiz','recruitment']),field('messageXp','XP por atividade textual','number'),field('messageCap','Teto diário de XP textual','number'),field('cooldownSeconds','Intervalo em segundos','number'),field('excludedChannels','Canais sem pontuação (IDs, um por linha)','lines'),field('adminRoles','Cargos administradores do RPG (IDs)','lines'),field('protectedRoles','Cargos protegidos (IDs)','lines'),field('advanced','Ativar recursos avançados','checkbox'),field('moderation','Ativar moderação delegada','checkbox'),field('captainTimeoutMinutes','Timeout máximo do capitão, em minutos','number'),field('viceTimeoutMinutes','Timeout máximo do vice, em minutos','number'),field('retentionDays','Retenção de atividade, em dias','number')
],async values=>{const preview=await act('settings.preview',values);$('#editor').close();setTimeout(()=>{void form('Confirmar regras',[field('confirm','Confirmo as regras apresentadas','checkbox',false)],input=>act('settings.save',{...values,...input}),`Teto de texto: ${preview.impact.dailyTextXp} XP/dia; até ${preview.impact.weeklyTextXp} XP/semana por participante.`);},0);return preview;},'',data)));
  root.append(button('Controles de emergência',()=>form('Suspender sistemas',[field('pausePoints','Suspender pontuação','checkbox',data.pausePoints),field('pauseMissions','Suspender missões','checkbox',data.pauseMissions),field('pauseModeration','Suspender moderação delegada','checkbox',data.pauseModeration),field('reason','Motivo','textarea')],values=>act('emergency',values))));
  root.append(detail('Fuso',data.timezone),detail('XP por atividade',data.messageXp),detail('Teto diário',data.messageCap),detail('Recursos avançados',data.advanced?'Ativados':'Desativados'),detail('Moderação delegada',data.moderation?'Ativada':'Desativada'));
}
function metrics(data){const root=$('#view');root.append(node('p','Os indicadores usam eventos registrados após a instrumentação. Coortes ainda incompletas aparecem como indisponíveis.','notice'));for(const [label,value] of [['Participantes cadastrados',data.members],['Participantes ativos',data.active],['Missões atribuídas',data.missions.assigned],['Missões concluídas',data.missions.completed],['Presenças validadas',data.events.attended],['Convites atribuídos',data.campaigns.attributed],['Convites qualificados',data.campaigns.qualified],['Retenção de 7 dias',data.retention7?`${data.retention7.returned} de ${data.retention7.eligible}`:'Ainda indisponível'],['Retenção de 30 dias',data.retention30?`${data.retention30.returned} de ${data.retention30.eligible}`:'Ainda indisponível']])root.append(detail(label,value));}
function render(kind,data){
  const toolbar=$('#toolbar');if(modules[kind].fields&&state.capabilities.admin)toolbar.append(button('Criar rascunho',()=>definition(kind),true));
  if(kind==='division'&&state.capabilities.leader)toolbar.append(button('Criar divisão',()=>form('Nova divisão',[field('number','Número','number',1),field('name','Nome'),field('color','Cor','color','#8B1E2D'),field('motto','Lema','textarea'),field('memberLimit','Vagas','number',25)],v=>act('division.save',v)),true));
  if(kind==='moderation'&&state.capabilities.admin)toolbar.append(button('Registrar ação',()=>form('Ação de moderação',[field('userId','Participante','member'),field('action','Ação','select','warn',['warn','timeout','delete','ticket','kick','ban']),field('reason','Motivo','textarea'),field('minutes','Duração em minutos','number',0),field('divisionId','Divisão (se aplicável)','optional'),field('channelId','Canal (para exclusão)','optional'),field('messageId','Mensagem (para exclusão)','optional')],v=>act('moderation.request',v))));
  if(kind==='relationship')toolbar.append(button('Propor relação',()=>form('Aliança ou rivalidade',[field('fromDivisionId','Sua divisão','division'),field('toDivisionId','Outra divisão','division'),field('type','Relação','select','alliance',['alliance','rivalry'])],v=>act('relationship.propose',v))));
  const search=document.createElement('input');search.type='search';search.placeholder='Buscar nesta seção';search.setAttribute('aria-label','Buscar nesta seção');search.value=query;search.addEventListener('change',()=>{query=search.value;page=1;void load();});toolbar.append(search);
  if(state.capabilities.admin)toolbar.append(button('Exportar esta página',async()=>download(await api.request(`/api/guilds/${encodeURIComponent(api.guild)}/${kind}?format=csv&page=${page}&q=${encodeURIComponent(query)}`),'jumanji.csv')));
  const cards=node('div','','cards');for(const row of data.items??[]){const card=node('article','','record-card'),d=row.data??row;
    card.append(node('span',labels[row.status]??row.status??'Participante','badge'),node('h2',d.name??d.display_name??d.text??d.action??d.kind??'Registro'));
    if(d.description??d.theme??d.body)card.append(node('p',d.description??d.theme??d.body));
    if(kind==='assignment'){card.append(detail('Progresso',`${d.progress}/${d.target}`));const progress=document.createElement('progress');progress.className='progress';progress.max=d.target;progress.value=d.progress;progress.setAttribute('aria-label','Progresso da missão');card.append(progress);}
    if(d.reward)card.append(detail('Recompensa',Object.entries(d.reward).filter(([,v])=>v).map(([k,v])=>`${v} ${k==='credits'?'créditos':k==='division'?'pontos da divisão':k.toUpperCase()}`).join(' · ')||'Sem pontos'));
    if(d.startsAt)card.append(detail('Início',new Date(d.startsAt).toLocaleString('pt-BR')));if(d.endsAt)card.append(detail('Prazo',new Date(d.endsAt).toLocaleString('pt-BR')));
    if(d.price!==undefined)card.append(detail('Preço',`${d.price} créditos`));if(d.xp!==undefined)card.append(detail('XP',d.xp));if(d.member_count!==undefined)card.append(detail('Ocupação',`${d.member_count}/${d.member_limit}`));
    if(d.reason)card.append(detail('Motivo',d.reason));if(d.last_error)card.append(node('p',d.last_error,'error'));if(d.result?.url){const a=node('a','Abrir convite');a.href=d.result.url;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}
    if(d.result?.winner)card.append(detail('Resultado',d.result.winner==='tie'?'Empate':`Divisão vencedora: ${d.result.winnerDivisionId}`));if(d.result?.left!==undefined)card.append(detail('Força calculada',`${d.result.left} × ${d.result.right}`));
    if(d.ranking)card.append(detail('Classificação final',d.ranking.map(r=>`${r.place}º — ${r.score} pontos`).join(' · ')||'Sem pontuação'));
    if(row.id)card.append(node('code',row.id));const actions=node('div','','toolbar');rowActions(kind,row,actions);card.append(actions);cards.append(card);
  }
  $('#view').append(data.items?.length?cards:node('p','Nenhum registro nesta seção. Novas atividades e configurações aparecerão aqui.','empty'));
  const pages=Math.max(1,Math.ceil((data.total??0)/25));const prev=button('Anterior',async()=>{page--;await load();});prev.disabled=page<=1;const next=button('Próxima',async()=>{page++;await load();});next.disabled=page>=pages;$('#pagination').append(prev,node('span',`${page} de ${pages} · ${data.total??0} registros`),next);
}
function rowActions(kind,row,root){const d=row.data??row,admin=state.capabilities.admin;
  const add=(label,action,data={id:row.id},fields=[],description='')=>root.append(button(label,()=>form(label,fields,input=>act(action,{...data,...input}),description)));
  if(row.status==='DRAFT'&&admin&&modules[kind].fields){root.append(button('Editar',()=>definition(kind,row)));add('Publicar','definition.publish',{kind,id:row.id});}
  if(kind==='division'&&d.status==='active'){add('Entrar','division.join',{divisionId:row.id});if(state.capabilities.leader){add('Convidar','division.invite',{divisionId:row.id},[field('userId','Participante','member')]);add('Nomear liderança','leadership.set',{divisionId:row.id},[field('userId','Participante','member'),field('position','Função','select','captain',['captain','vice-captain']),field('reason','Motivo','textarea')]);add('Remover liderança','leadership.remove',{divisionId:row.id},[field('position','Função','select','captain',['captain','vice-captain']),field('reason','Motivo','textarea')]);add('Arquivar','division.archive',{id:row.id});}}
  if(kind==='member'&&admin){add('Transferir','division.transfer',{userId:row.user_id},[field('divisionId','Destino','division'),field('reason','Motivo','textarea')]);add('Ajustar pontos','points.adjust',{userId:row.user_id,eventKey:crypto.randomUUID()},[field('type','Tipo','select','xp',['xp','honor','influence','credits']),field('amount','Quantidade (negativa para remover)','number',0),field('reason','Motivo','textarea')]);}
  if(kind==='assignment'&&['ACTIVE','CHANGES_REQUESTED','REJECTED'].includes(row.status))add('Enviar prova externa','proof.submit',{assignmentId:row.id},[field('url','URL pública da prova','url')],'Use somente para missões com revisão externa.');
  if(kind==='submission'&&admin){if(d.url){const link=node('a','Abrir prova');link.href=d.url;link.target='_blank';link.rel='noopener noreferrer';root.append(link);}if(d.fileId){const link=node('a','Ver imagem');link.href=`/api/guilds/${encodeURIComponent(api.guild)}/files/${d.fileId}`;link.target='_blank';link.rel='noopener';root.append(link);}if(row.status==='PENDING')add('Revisar','proof.review',{id:row.id},[field('decision','Decisão','select','APPROVED',['APPROVED','REJECTED','CHANGES_REQUESTED']),field('reason','Motivo','textarea')]);}
  if(kind==='event'&&row.status==='ACTIVE'){add('Inscrever-se','event.rsvp');add('Cancelar inscrição','event.cancel');if(admin)add('Validar presença','event.checkin',{id:row.id},[field('userId','Participante','member'),field('reason','Como a presença foi confirmada','textarea')]);}
  if(kind==='campaign'&&row.status==='ACTIVE')add('Gerar meu convite','campaign.invite');
  if(kind==='season'&&admin){if(row.status==='ACTIVE')add('Encerrar temporada','season.finish');if(row.status==='FINISHED')add('Arquivar temporada','season.archive');}
  if(kind==='item'&&row.status==='ACTIVE')add('Adquirir cosmético','shop.buy',undefined,[],`Custo: ${d.price} créditos cosméticos.`);
  if(kind==='inventory')add(d.equipped?'Equipado':'Equipar','inventory.equip');
  if(kind==='battle'){if(row.status==='RECRUITING'){add('Inscrever-se','battle.enroll');if(admin)add('Iniciar rodada','battle.start');}if(row.status==='ACTIVE'){add('Escolher estratégia','battle.strategy',{id:row.id},[field('strategy','Estratégia','select','defend',['attack','defend','maneuver'])]);if(admin)add('Apurar resultado','battle.resolve');}}
  if(kind==='chapter'&&row.status==='ACTIVE')add('Votar','chapter.vote',{id:row.id},[field('choice','Sua escolha','select','0',d.choices.map((label,i)=>({value:String(i),label}))) ]);
  if(kind==='challenge'&&row.status==='ACTIVE')add('Participar','challenge.enter',{id:row.id},d.type==='quiz'?[field('answer',d.question,'number',0)]:['memes','creative'].includes(d.type)?[field('url','URL do seu conteúdo','url')]:[]);
  if(kind==='election'&&row.status==='ACTIVE'){add('Candidatar-se','election.nominate',{id:row.id},[field('statement','Sua proposta','textarea')]);add('Votar','election.vote',{id:row.id},[field('userId','Candidato','member')]);}
  if(kind==='relationship'&&row.status==='PENDING')add('Aceitar proposta','relationship.accept');
  if(kind==='territory'&&admin)add('Atribuir território','territory.assign',{id:row.id},[field('divisionId','Divisão','division'),field('reason','Motivo','textarea')]);
  if(kind==='moderation'&&admin){if(row.status==='AWAITING_APPROVAL')add('Aprovar ação','moderation.approve',{id:row.id},[field('confirm','Confirmo a ação','checkbox',false),field('reason','Motivo','textarea')]);if(['OPEN','APPEALED','FAILED','ACTIONED'].includes(row.status))add('Resolver caso','moderation.resolve',{id:row.id},[field('reason','Decisão e justificativa','textarea')]);}
  if(kind==='job'&&row.status==='failed')add('Tentar novamente','job.retry');
}
function templates(){return form('Gerar rascunho por template',[field('template','Conteúdo','select','mission',['mission','campaign','journal','summary']),field('name','Título'),field('objective','Objetivo e contexto','textarea'),field('campaignTemplate','Modelo de campanha','select','recruitment',['recruitment','emblems','recruits','operation','chronicle'])],v=>act('template.generate',v),'Templates usam dados reais do servidor e não fazem chamadas a serviços de IA.');}
async function initialize(){const origin=(window.JUMANJI_API_ORIGIN||'').replace(/\/$/,'');$('#login').href=origin+'/api/auth/login';try{const session=await api.request('/api/me');me=session.user;api.csrf=session.csrf;$('#identity').textContent=me.name;$('#login').hidden=true;$('#logout').hidden=false;$('#refresh').hidden=false;const guilds=await api.request('/api/guilds');$('#guild').replaceChildren();for(const guild of guilds.items){const option=node('option',guild.name);option.value=guild.id;$('#guild').append(option);}api.guild=$('#guild').value;if(api.guild)await load();else feedback('O bot ainda não está disponível em um servidor da sua conta.');}catch(error){if(error.status!==401)feedback(error.message,true);$('#view').append(node('p','Acesse sua conta Discord para visualizar dados reais e participar da comunidade.','empty'));}}
$('#guild').addEventListener('change',()=>{api.guild=$('#guild').value;page=1;query='';void load();});
$('#refresh').addEventListener('click',()=>{void load();});$('#logout').addEventListener('click',async()=>{try{await api.request('/api/auth/logout',{method:'POST'});location.reload();}catch(e){feedback(e.message,true);}});
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));});
window.addEventListener('hashchange',()=>{page=1;query='';$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');void load();});
function dashboard2(data){
  const root=$('#view'),stats=node('div','','stats-grid');
  const values=[['SEU XP',data.member?.xp??0,'progresso pessoal'],['CRÉDITOS',data.member?.credits??0,'para itens cosméticos'],['PARTICIPANTES',data.stats?.members??0,'na base hoje'],['DIVISÕES',data.stats?.divisions??0,'territórios ativos']];
  for(const [label,value,caption] of values){const card=node('article','','stat-card');const body=node('div');body.append(node('span',label),node('strong',String(value)),node('small',caption));card.append(body);stats.append(card)}root.append(stats);
  const grid=node('div','','dashboard-grid');
  const action=node('article','','record-card action-card');action.append(node('div','01 · PRÓXIMO PASSO','eyebrow'),node('h2',data.member?.participation==='active'?'A base está esperando por você.':'Seu lugar na história ainda está aberto.'));
  action.append(node('p',data.member?.participation==='active'?'Escolha uma missão, fortaleça sua divisão ou entre no próximo evento.':'Entre pelo Discord e deixe o bot registrar apenas as atividades que você escolher compartilhar.'));
  action.append(data.member?.participation==='active'?button('Abrir minhas missões →',()=>{location.hash='assignment'},true):button('Aceitar e participar →',async()=>{await act('consent',{accept:true});await load()},true));grid.append(action);
  const season=node('article','','record-card season-card');season.append(node('div','02 · SINAL DA TEMPORADA','eyebrow'));
  if(data.season){season.append(node('h2',data.season.data.name||'Temporada ativa'),node('p',data.season.data.theme||'A próxima fase da campanha começa no Discord.'))}else{season.append(node('h2','Nenhuma temporada ativa'),node('p','O próximo capítulo será transmitido direto nos canais da comunidade.'))}
  season.append(node('div','ABRA O DISCORD · RECEBA O SINAL','season-code'));grid.append(season);root.append(grid);
  if(data.campaign){const campaign=node('article','','campaign-banner');campaign.append(node('div','03 · CAMPANHA ATIVA','eyebrow'),node('h2',data.campaign.data.name||'Operação da semana'),node('p',data.campaign.data.description||'Convide pessoas que combinam com a comunidade e acompanhe quem realmente participa.'),node('span',`${data.campaign.data.template||'comunidade'} · convite qualificado`));root.append(campaign)}
  const pulse=node('section','','pulse-section');pulse.append(node('div','PULSO DA BASE','eyebrow'),node('h2','Tudo acontece em comunidade.'));const chips=node('div','','command-chips');for(const [cmd,desc] of [['/missao','ver seus objetivos'],['/divisao','encontrar sua equipe'],['/ranking','consultar a disputa']]){const chip=node('div','','command-chip');chip.append(node('code',cmd),node('span',desc));chips.append(chip)}pulse.append(chips);root.append(pulse);
  if(data.capabilities?.admin){$('#toolbar').append(button('Configurar base',()=>setup()),button('Sincronizar membros',()=>ask('Sincronizar membros','members.sync',{},[],'Cadastra humanos como recrutas; não concede consentimento.')),button('Criar conteúdo por template',()=>templates()));if(data.jobs?.length){const ops=node('article','','record-card');ops.append(node('h2','Operações recentes'));for(const job of data.jobs)ops.append(detail(job.kind,labels[job.status]??job.status));ops.append(button('Acompanhar tarefas →',()=>{location.hash='job'}));root.append(ops)}}
}
void initialize();

