export const field=(key,label,type='text',value='',options=[])=>({key,label,type,value,options});
const f=field;
const reward=[f('reward.xp','XP','number',25),f('reward.honor','Honra','number',0),f('reward.influence','Influência','number',0),f('reward.credits','Créditos cosméticos','number',5),f('reward.division','Pontos da divisão','number',5)];
const tomorrow=()=>new Date(Date.now()+86400000).toISOString().slice(0,16);
const week=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,16);
const name=f('name','Nome'),description=f('description','Descrição e critérios','textarea');
const select=(key,label,options,value=options[0])=>f(key,label,'select',value,options);
export const modules={
  dashboard:{label:'Visão geral',group:'Sua jornada'},assignment:{label:'Minhas missões',group:'Sua jornada'},division:{label:'Divisões',group:'Sua jornada'},ranking:{label:'Ranking',group:'Sua jornada'},event:{label:'Eventos',group:'Sua jornada',fields:[name,description,f('startsAt','Início','datetime-local',tomorrow()),f('endsAt','Encerramento','datetime-local',week()),...reward]},
  inventory:{label:'Inventário',group:'Sua jornada'},item:{label:'Loja cosmética',group:'Sua jornada',fields:[name,description,select('slot','Tipo',['title','frame','emblem','banner','pet']),f('price','Preço em créditos','number',10),f('color','Cor','color','#D4A72C')]},
  privacy:{label:'Privacidade',group:'Sua jornada'},season:{label:'Temporadas',group:'Comunidade',fields:[name,f('theme','Tema e sinopse','textarea')]},campaign:{label:'Campanhas',group:'Comunidade',fields:[name,description,select('template','Modelo',['recruitment','emblems','recruits','operation','chronicle']),f('endsAt','Encerramento','datetime-local',week()),f('qualificationDays','Dias para qualificação','number',7),f('activeDays','Dias de atividade exigidos','number',2),f('weeklyCap','Limite semanal por membro','number',5),...reward]},
  battle:{label:'Batalhas',group:'Comunidade',fields:[name,f('divisionIds.0','Primeira divisão','division'),f('divisionIds.1','Segunda divisão','division'),f('cap','Limite por participante','number',100),f('durationHours','Duração em horas','number',24),...reward]},
  chapter:{label:'História e votações',group:'Comunidade',fields:[name,f('body','Capítulo','textarea'),f('seasonId','Temporada','season'),f('choices','Opções, uma por linha','lines','Reunir aliados\nExplorar o território'),f('endsAt','Fim da votação','datetime-local',week())]},
  challenge:{label:'Desafios e chefes',group:'Comunidade',fields:[name,select('type','Tipo',['boss','quiz','memes','creative']),description,f('endsAt','Encerramento','datetime-local',week()),f('targetPerMember','Meta por participante','number',50),f('question','Pergunta do quiz','optional'),f('options','Alternativas, uma por linha','lines',''),f('answer','Número da resposta correta (começando em 0)','number',0),...reward]},
  achievement:{label:'Conquistas',group:'Comunidade',fields:[name,description,select('metric','Critério',['xp','missions','events','invites']),f('target','Quantidade','number',100),f('secret','Conquista secreta','checkbox',false),...reward]},
  territory:{label:'Territórios',group:'Comunidade',fields:[name,description]},election:{label:'Eleições',group:'Comunidade',fields:[name,f('divisionId','Divisão','division'),select('position','Função',['captain','vice-captain']),f('endsAt','Fim da eleição','datetime-local',week())]},journal:{label:'Jornal da base',group:'Comunidade',fields:[name,f('body','Conteúdo','textarea')]},relationship:{label:'Alianças e rivalidades',group:'Comunidade'},
  mission:{label:'Biblioteca de missões',group:'Administração',admin:true,fields:[name,description,select('action','Validação',['text','onboarding','voice','reaction','event','external','welcome']),f('target','Meta (voz em segundos)','number',1),select('period','Repetição',['once','daily','weekly','season']),f('messageId','Mensagem da reação','optional'),f('externalUrl','URL da campanha externa','optional'),...reward]},
  member:{label:'Participantes e liderança',group:'Administração',admin:true},submission:{label:'Revisar provas',group:'Administração',admin:true},moderation:{label:'Moderação',group:'Administração',admin:true},metrics:{label:'Métricas',group:'Administração',admin:true},experiment:{label:'Experimentos',group:'Administração',admin:true,fields:[name,f('hypothesis','Hipótese','textarea'),select('variable','Variável',['event_time','announcement_text','mission_duration']),f('control','Configuração de controle'),f('variant','Variação'),f('startsAt','Início','datetime-local',tomorrow()),f('endsAt','Fim','datetime-local',week()),select('metric','Métrica',['mission_completion','event_attendance','activation'])]},
  webhook:{label:'Integrações',group:'Administração',admin:true,fields:[name,f('url','URL HTTPS de destino','url'),f('secret','Segredo de assinatura (mínimo 32 caracteres)','password')]},audit:{label:'Auditoria',group:'Administração',admin:true},job:{label:'Tarefas',group:'Administração',admin:true},settings:{label:'Configurações',group:'Administração',admin:true}
};
export const labels={ACTIVE:'Ativo',DRAFT:'Rascunho',SCHEDULED:'Agendado',PENDING:'Pendente',UNDER_REVIEW:'Em revisão',COMPLETED:'Concluído',FINISHED:'Encerrado',APPROVED:'Aprovado',REJECTED:'Rejeitado',CHANGES_REQUESTED:'Correção solicitada',ARCHIVED:'Arquivado',OWNED:'Adquirido',RECRUITING:'Inscrições abertas',pending:'Na fila',running:'Em andamento',done:'Concluída',failed:'Falhou',cancelled:'Cancelada',attack:'Ataque',defend:'Defesa',maneuver:'Manobra',captain:'Capitão','vice-captain':'Vice-capitão',text:'Texto',voice:'Voz',reaction:'Reação',external:'Prova externa',onboarding:'Entrada no RPG',event:'Evento',welcome:'Acolhimento',once:'Uma vez',daily:'Diária',weekly:'Semanal',season:'Temporada',title:'Título',frame:'Moldura',emblem:'Emblema',banner:'Banner',pet:'Mascote',boss:'Chefe cooperativo',quiz:'Quiz',memes:'Batalha de memes',creative:'Desafio criativo',recruitment:'Recrutamento da semana',emblems:'Guerra dos emblemas',recruits:'Semana do recruta',operation:'Noite de operação',chronicle:'Crônica da comunidade'};
